### ISSUE TITLE
Semantic of parameter `end_of_stream` for `proxy_on_http_*_headers()` differs from Envoy.

### ISSUE THREAD

**Issue by andytesti** [Kong/ngx_wasm_module#504]
During the headers processing, ngx_wasm_module invokes the last `proxy_on_http_request_headers()` with the `end_of_stream` parameter set to `true`, regardless of whether a body has been sent or not. Its meaning seems to be "Has the header stream ended?" 
On the other hand, when a request contains a body in Envoy's proxy-wasm, the `end_of_stream` parameter for `proxy_on_http_request_headers()` is set to `false`. Its meaning appears to be "Has the entire transmission finished?" In the case where no body has been sent, `end_of_stream` is set to `true`. 
The same situation occurs with proxy_on_http_response_headers().

**Comment by thibaultcha** [comment]
Hi, thanks for noticing and reporting!

**Comment by thibaultcha** [comment]
Now I recall this has to do with it being very tricky to determine whether a request has a body or not from within Nginx without it being a costly operation. I am not sure we can improve this, we'll see.

**Comment by thibaultcha** [comment]
@andytesti Hi,

Would you be able to share the code of the filter you are using for a case study? Due to internal Nginx constraints when reading request/response bodies, it will be difficult or downright impossible to make this argument reliable in the RequestHeaders/ResponseHeaders steps. 

I went with a more accurate approach for now in #514, which always sets `eof=false` for those phases the flag cannot be relied upon.

If you could share the code or use-case for this flag in your filter, that would let us know if we need to invest significant effort or if usage of the flag can simply be bypassed by filters.

Thanks

**Comment by andytesti** [comment]
Hi @thibaultcha, thanks for addressing this issue!
We have a Rust high-level proxy-wasm development framework where the data-flow is managed in an opinionated way, as we want to keep our users away from proxy-wasm oddities. We would like to keep it portable across proxy-wasm implementations.
Instead of following the default suggested reactor pattern and implementing `RootContext` and `HttpContext` interfaces for defining filters, our framework allows to write a filter as an `async` function. Every HTTP event can be `.await`ed inside the filter function.
Our framework holds an internal state-machine that keeps track of the HTTP context events to determine if a filter task must be **cancelled** or not.
The most common case where our framework considers that a filter is **cancelled**, is when a request is being processed, and an upstream filter returns an early `send_response()` during his own `proxy_on_http_request_headers()`. In this case, even though the request has a body, the `proxy_on_http_request_body()` function is never called. If the `proxy_on_request_headers()`'s `end_of_stream` parameter is `true`, and the `proxy_on_request_body()` is never called, we know that our filter task must be cancelled.
There is a more expensive and less robust alternative that consists in evaluate headers like `Content-Length` during `proxy_on_http_request_headers()` and determine if there is a body stream.

**Comment by andytesti** [comment]
The framework is written in Rust, since writing a concurrency runtime in tinygo was not possible at the moment (and I guess it is still not possible).
Other Rust features like move semantics and type-state pattern allowed us to deal with proxy-wasm buffer invalidation (i.e. forbidding access to headers during body events). As you mention, the cost is not being cross-language, but we try to keep Rust easy, even for newcomers. You can check our [docs](https://docs.mulesoft.com/pdk/latest/policies-pdk-overview) and [examples](https://docs.mulesoft.com/pdk/latest/policies-pdk-policy-templates).
I actually tested the framework with this module and it worked fine after a couple of changes (I tested changing `end_of_stream` by checking the `Content-Lenght` header). Still have to do perform many tests, but for the happy path it looks great.

**Comment by andytesti** [comment]
Sure! You can close it. I will be giving you more feedback while continue testing.
Thank you very much for addressing this issue and for all the great work you are doing with this nice module.

**Comment by thibaultcha** [comment]
Great, cheers!
